language: objective-c
xcode_workspace: Example/APNPermissionRequest.xcworkspace
xcode_scheme: APNPermissionRequest-Example
podfile: Example/Podfile
script:
  - xctool -workspace Example/APNPermissionRequest.xcworkspace -scheme 'APNPermissionRequest-Example' -sdk iphoneos build CODE_SIGNING_REQUIRED=NO
